<<<<<<< HEAD
=======
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopInfo from "@/components/TopInfo";
import Logo from "@/components/Logo";
import NavBar from "@/components/NavBar";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import MobileInterface from "@/components/MobileInterface";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Osta-Demo E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
       
          <TopInfo />
          <Logo />
          <NavBar />
          <MobileInterface />
          {children}
          <Footer />
    
        </body>
    </html>
  );
}
>>>>>>> 9515f8b (styles changes)
